language: python
sudo: false
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
  matrix:
    - TOXENV=check
    - TOXENV=docs
matrix:
  include:
{% for env in tox_environments %}
    - python: {{ env.split('-')[0] if env.startswith('pypy') else '{0[2]}.{0[3]}'.format(env) }}
      env:
        - TOXENV={{ env }},report,coveralls,codecov
{% endfor %}
before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then deactivate && wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-5.7-linux_x86_64-portable.tar.bz2 && tar -jxvf pypy-5.7-linux_x86_64-portable.tar.bz2 && echo 'Setting up aliases...' && export PATH=$HOME/pypy-5.7-linux_x86_64-portable/bin/:$PATH && ln -s ~/pypy-5.7-linux_x86_64-portable/bin/pypy ~/bin/python && echo 'Setting up pip...' && pypy-5.7-linux_x86_64-portable/bin/pypy -m ensurepip ; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then deactivate && wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.5-5.7-beta-linux_x86_64-portable.tar.bz2 && tar -jxvf pypy3.5-5.7-beta-linux_x86_64-portable.tar.bz2 && echo 'Setting up aliases...' && export PATH=$HOME/pypy3.5-5.7-beta-linux_x86_64-portable/bin/:$PATH && ln -s ~/pypy3.5-5.7-beta-linux_x86_64-portable/bin/pypy3.3 ~/bin/python && echo 'Setting up pip...' && pypy3.5-5.7-beta-linux_x86_64-portable/bin/pypy -m ensurepip && ln -s ~/pypy3.5-5.7-beta-linux_x86_64-portable/bin/pip3.5 ~/bin/pip ; fi"
install:
  - pip install tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
